logging:
  level:
    org.springframework: INFO
    contacts: DEBUG

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring-jmx
    username: root
    password: 1234
    initialize: true	        
init-db: true